name: CD to Staging

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo on GitHub Actions runner
      - uses: actions/checkout@v4

      # Setup QEMU (required for cross-platform Docker builds)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} -f trade-capture/Dockerfile trade-capture
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      # Deploy to staging via SSH
      - name: Deploy to staging via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.STAGING_PORT }}
          script: |
            cd ~ || mkdir -p ~

            # If staging folder exists and is a git repo, pull latest changes
            if [ -d "gravitas-staging" ]; then
              if [ -d "gravitas-staging/.git" ]; then
                cd gravitas-staging
                git reset --hard
                git pull
              else
                # Remove folder if not a git repo
                rm -rf gravitas-staging
                git clone https://github.com/ramankrishnan/ETRM-devops.git gravitas-staging
                cd gravitas-staging
              fi
            else
              # Clone repo if folder doesn't exist
              git clone https://github.com/ramankrishnan/ETRM-devops.git gravitas-staging
              cd gravitas-staging
            fi

            # Install Docker & Compose if missing
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
            fi

            # Write .env file from GitHub secret
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

            # Pull latest images and start services
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans

