name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: ./trade-capture
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests with PYTHONPATH
      - name: Run tests
        working-directory: ./trade-capture
        run: |
          export PYTHONPATH=$(pwd)
          pytest -q

      # Step 5: Build Docker image (optional)
      - name: Build Docker image (optional check)
        run: docker build -t gravitas-trade-capture:ci --file trade-capture/Dockerfile trade-capture
